conf_api/urls.py
from django.conf.urls import patterns, include, url

from rest_framework import routers

from .views import ConferenceViewset, CurrentConferenceView, ScheduleViewSet, SlotViewSet, PresentationViewSet

router = routers.DefaultRouter()
router.register(r'conferences', ConferenceViewset)
router.register(r'schedule', ScheduleViewSet)
router.register(r'slots', SlotViewSet)
router.register(r'presentations', PresentationViewSet)


urlpatterns = patterns(
    "",
    url(r'^', include(router.urls)),
    url(r'^conference$', CurrentConferenceView.as_view(), name='current_conference'),
    url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
)

symposion2016/conf_api/urls.py
from django.conf.urls import patterns, include, url

from rest_framework import routers

from .views import ConferenceViewset, CurrentConferenceView, TalkProposalView

router = routers.DefaultRouter()
router.register(r'conferences', ConferenceViewset)
router.register(r'proposals', TalkProposalView)


urlpatterns = patterns(
    "",
    url(r'^', include(router.urls)),
    url(r'^conference$', CurrentConferenceView.as_view(), name='current_conference'),
    url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
)

symposion2016/urls.py
from collections import OrderedDict

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin
from account.views import LoginView, SignupView
from account.forms import SignupForm
from account.forms import LoginEmailForm
from django.contrib.auth import get_user_model

import symposion.views


WIKI_SLUG = r"(([\w-]{2,})(/[\w-]{2,})*)"


class LoginEmailView(LoginView):
    form_class = LoginEmailForm


class NoUsernameSignUpForm(SignupForm):
    username = None

    def __init__(self, *args, **kwargs):
        super(NoUsernameSignUpForm, self).__init__(*args, **kwargs)

        order = ['email', 'password', 'password_confirm', 'code']
        self.fields = OrderedDict(sorted(self.fields.items(),
                                         key=lambda t: order.index(t[0]) if t[0] in order else len(order)))


class NoUsernameSignUpView(SignupView):
    form_class = NoUsernameSignUpForm

    def generate_username(self, form):
        email = form.cleaned_data['email']
        new_username = email.split('@')[0]
        User = get_user_model()
        c = 1
        while User.objects.filter(username=new_username+str(c)).exists():
            c += 1

        return new_username + str(c)

urlpatterns = patterns(
    "",
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include(admin.site.urls)),

    # url(r"^account/signup/$", symposion.views.SignupView.as_view(), name="account_signup"),
    # url(r"^account/login/$", symposion.views.LoginView.as_view(), name="account_login"),
    url(r"^account/login/$", LoginEmailView.as_view(), name="account_login"),
    url(r"^account/signup/$", NoUsernameSignUpView.as_view(), name="account_signup"),
    url(r"^account/", include("account.urls")),

    url(r"^dashboard/", symposion.views.dashboard, name="dashboard"),
    url(r"^speaker/", include("symposion.speakers.urls")),
    url(r"^proposals/", include("symposion.proposals.urls")),
    url(r"^sponsors/", include("symposion.sponsorship.urls")),
    url(r"^teams/", include("symposion.teams.urls")),
    url(r"^reviews/", include("symposion.reviews.urls")),
    url(r"^schedule/", include("symposion.schedule.urls")),
    url(r"^markitup/", include("markitup.urls")),
    url(r"^boxes/", include("pinax.boxes.urls")),

    url(r"^api/", include('symposion2016.conf_api.urls')),

    # url(r"^", include("symposion.cms.urls")),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

symposion_test/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin

from rest_framework import routers

import symposion.views


WIKI_SLUG = r"(([\w-]{2,})(/[\w-]{2,})*)"

router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)


urlpatterns = patterns(
    "",
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include(admin.site.urls)),

    # url(r"^account/signup/$", symposion.views.SignupView.as_view(), name="account_signup"),
    # url(r"^account/login/$", symposion.views.LoginView.as_view(), name="account_login"),
    url(r"^account/", include("account.urls")),

    url(r"^dashboard/", symposion.views.dashboard, name="dashboard"),
    url(r"^speaker/", include("symposion.speakers.urls")),
    url(r"^proposals/", include("symposion.proposals.urls")),
    url(r"^sponsors/", include("symposion.sponsorship.urls")),
    # url(r"^boxes/", include("symposion.boxes.urls")),
    url(r"^teams/", include("symposion.teams.urls")),
    url(r"^reviews/", include("symposion.reviews.urls")),
    url(r"^schedule/", include("symposion.schedule.urls")),
    url(r"^markitup/", include("markitup.urls")),

    # url(r"^", include("symposion.cms.urls")),


    url(r"^api/", include('conf_api.urls'))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

symposion2016/pycon_proposals/models.py
from django.db import models
from django.utils.text import ugettext_lazy as _

from symposion.proposals.models import ProposalBase


class Proposal(ProposalBase):

    AUDIENCE_LEVEL_NOVICE = 1
    AUDIENCE_LEVEL_EXPERIENCED = 2
    AUDIENCE_LEVEL_INTERMEDIATE = 3

    AUDIENCE_LEVELS = [
        (AUDIENCE_LEVEL_NOVICE, "Novice"),
        (AUDIENCE_LEVEL_INTERMEDIATE, "Intermediate"),
        (AUDIENCE_LEVEL_EXPERIENCED, "Experienced"),
    ]

    audience_level = models.IntegerField(choices=AUDIENCE_LEVELS)

    recording_release = models.BooleanField(
        default=True,
        help_text="By submitting your proposal, you agree to give permission to the conference organizers to record,"
                  " edit, and release audio and/or video of your presentation. If you do not agree to this, "
                  "please uncheck this box."
    )

    YES = 1
    NO = 0
    YES_NO_CHOICES = ((YES, 'Yes'), (NO, 'No'))

    recurring = models.PositiveSmallIntegerField(choices=YES_NO_CHOICES,
                                                 default=0,
                                                 help_text=_("Have you given this talk before?"),
                                                 verbose_name=_("Previously given"))
    tutorial = models.PositiveSmallIntegerField(choices=YES_NO_CHOICES,
                                                default=0,
                                                help_text=_("Would you be interested in receiving mentorship /"
                                                            " input on your talk in advance?"),
                                                verbose_name=_("Speaker mentorship"))

    DURATION_SHORT = 'short'
    DURATION_MEDIUM = 'medium'
    DURATION_LONG = 'long'
    DURATION_CHOICES = (
        (DURATION_SHORT, 'Short (~10 minutes)'),
        (DURATION_MEDIUM, 'Long (~30 minutes)'),
        (DURATION_LONG, 'Classroom tutorial (~45-60 minutes)'),
    )

    duration = models.CharField(choices=DURATION_CHOICES,
                                max_length=16,
                                default=DURATION_MEDIUM,
                                verbose_name=_("Duration"))

    class Meta:
        abstract = True

    @property
    def duration_display(self):
        return dict(self.DURATION_CHOICES).get(self.duration)

    @property
    def tutorial_display(self):
        return 'Yes' if self.tutorial else 'No'

    @property
    def recurring_display(self):
        return 'Yes' if self.recurring else 'No'


class TalkProposal(Proposal):

    class Meta:
        verbose_name = "talk proposal"
        permissions = (
            ('can_review_unbiased', 'Can review with speaker details'),
        )


class TutorialProposal(Proposal):
    class Meta:
        verbose_name = "tutorial proposal"

symposion2016/pycon_proposals/forms.py
from django import forms

from markitup.widgets import MarkItUpWidget

from .models import TalkProposal, TutorialProposal


class ProposalForm(forms.ModelForm):

    def clean_description(self):
        value = self.cleaned_data["description"]
        if len(value) > 400:
            raise forms.ValidationError(
                u"The description must be less than 400 characters"
            )
        return value


class TalkProposalForm(ProposalForm):

    class Meta:
        model = TalkProposal
        fields = [
            "title",
            "audience_level",
            "description",
            "abstract",
            "recurring",
            "tutorial",
            "duration",
            "additional_notes",
            "recording_release",
        ]
        widgets = {
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }


class TutorialProposalForm(ProposalForm):

    class Meta:
        model = TutorialProposal
        fields = [
            "title",
            "audience_level",
            "description",
            "abstract",
            "additional_notes",
            "recording_release",
        ]
        widgets = {
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }

symposion2016/conf_api/views.py
from django.shortcuts import render
from rest_framework import viewsets, views
from rest_framework.response import Response

from symposion.conference.models import Conference, Section, current_conference
from symposion.schedule.models import Schedule, Session, Day, Room, Slot, SlotKind, SlotRoom, Presentation, SessionRole
from symposion2016.pycon_proposals.models import TalkProposal
from .serializers import TalkSerializer, ConferenceSerializer, SectionSerializer


# CONFERENCE

class ConferenceViewset(viewsets.ModelViewSet):
    queryset = Conference.objects.all()
    serializer_class = ConferenceSerializer
    http_method_names = ('get', 'head', 'options',)


class CurrentConferenceView(views.APIView):
    http_method_names = ('get', 'head', 'options',)

    def get(self, request, format=None):
        conf = current_conference()
        conf_serializer = ConferenceSerializer(instance=conf)

        return Response(data=conf_serializer.data)


class TalkProposalView(viewsets.ModelViewSet):
    queryset = TalkProposal.objects.all()
    serializer_class = TalkSerializer
    http_method_names = ('get', 'head', 'options',)

symposion2016/prettyschedule/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.generic.base import TemplateView

from symposion.schedule.models import Day, Presentation

from timetable import TimeTable

class ScheduleView(TemplateView):
    template_name = 'prettyschedule/schedule.html'

    def get(self, request):
        if not request.user.is_authenticated or not request.user.is_staff:
            raise Http404()

        days_qs = Day.objects.all()
        days = [ TimeTable(day) for day in days_qs ]

        return self.render_to_response({
            'days': days
        })


class PresentationView(TemplateView):
    template_name = 'prettyschedule/presentation.html'

    def get(self, request, pk, *args, **kwargs):
        presentation = get_object_or_404(Presentation, proposal_base_id=pk)

        return self.render_to_response({
            'p': presentation
        })

symposion2016/templates/symposion/proposals/_pending_proposal_row.html
{% load i18n %}

<tr>
    <td>
        <a href="{% url "proposal_detail" proposal.pk %}">{{ proposal.title }}</a>
    </td>

    <td>{{ proposal.kind.name }}</td>

    <td>
        {% if proposal.cancelled %}
            <span class="label label-danger">{% trans 'Cancelled' %}</span>
        {% else %}
            {% if request.user == proposal.speaker.user %}
                {% if proposal.result.status == "accepted" %}
                    <span class="label label-success">{% trans 'Accepted' %}</span>
                {% else %}
                    <span class="label label-default">{% trans 'Submitted' %}</span>
                {% endif %}
            {% else %}
                <span class="label label-default">{% trans 'Invited' %}</span>
            {% endif %}
        {% endif %}
    </td>

    <td>
        {% if not proposal.cancelled %}
            <div class="btn-group">
                <a class="btn btn-xs dropdown-toggle" data-toggle="dropdown" href="#">
                {% trans 'Choose Response' %}
                <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url "proposal_pending_join" proposal.id %}">
			{% trans 'Accept invitation' %}</a></li>
                    <li><a href="{% url "proposal_pending_decline" proposal.id
		    %}">{% trans 'Decline invitation' %}</a></li>
                </ul>
            </div>
        {% endif %}
    </td>
</tr>

symposion2016/templates/symposion/proposals/_proposal_fields.html
{% load i18n %}

{% with perms.pycon_proposals.can_review_unbiased as biased %}
<dl class="dl-horizontal">
    {% if biased %}
        <dt>{% trans "Submitted by" %}</dt>
        <dd>{{ proposal.speaker }}</dd>
    {% endif %}

    <dt>{% trans "Track" %}</dt>
    <dd>{{ proposal.track }}&nbsp;</dd>

    <dt>{% trans "Audience Level" %}</dt>
    <dd>{{ proposal.get_audience_level_display }}&nbsp;</dd>

    <dt>{% trans "Duration" %}</dt>
    <dd>{{ proposal.duration_display }}&nbsp;</dd>

    <dt>{% trans "Tutorial" %}</dt>
    <dd>{{ proposal.tutorial_display }}&nbsp;</dd>

    <dt>{% trans "Given before" %}</dt>
    <dd>{{ proposal.recurring_display }}&nbsp;</dd>

    {% if proposal.additional_speakers.all %}
        <dt>{% trans "Additional Speakers" %}</dt>
        <dd>
            {% for speaker in proposal.additional_speakers.all %}
                <li>
                    {% if speaker.user %}
                        <strong>{{ speaker.name }}</strong> &lt;{{ speaker.email }}&gt;
                    {% else %}
                        {{ speaker.email }} ({% trans "Invitation Sent" %})
                    {% endif %}
                </li>
            {% endfor %}
        </dd>
    {% endif %}

    <dt>{% trans "Description" %}</dt>
    <dd>{{ proposal.description }}&nbsp;</dd>

    <dt>{% trans "Abstract" %}</dt>
    <dd>{{ proposal.abstract_html|safe }}&nbsp;</dd>

    <dt>{% trans "Notes" %}</dt>
    <dd>{{ proposal.additional_notes_html|safe }}&nbsp;</dd>

    {% if biased %}
        <dt>{% trans "Speaker Bio" %}</dt>
        <dd>{{ proposal.speaker.biography_html|safe }}&nbsp;</dd>
    {% endif %}

    <dt>{% trans "Documents" %}</dt>
    <dd>
        {% if proposal.supporting_documents.exists %}
            <table class="table table-striped">
                {% for document in proposal.supporting_documents.all %}
                    <tr>
                        <td><a href="{{ document.download_url }}">{{ document.description }}</a></td>
                        <td>
                        <form style="margin: 0;" method="post" action="{% url "proposal_document_delete" document.pk %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-xs">delete</button>
                        </form>
                    </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            No supporting documents attached to this proposal.
        {% endif %}
    </dd>
</dl>
{% endwith %}

symposion2016/templates/symposion/proposals/_proposal_row.html
<tr>
    <td>
        <a href="{% url "proposal_detail" proposal.pk %}">{{ proposal.title }}</a>
    </td>

    <td>{{ proposal.kind.name }}</td>

    <td>
        {% if proposal.cancelled %}
            <span class="label label-danger">Cancelled</span>
        {% else %}
            {% if request.user == proposal.speaker.user %}
                {% if proposal.result.status == "accepted" %}
                    <span class="label label-success">Accepted</span>
                {% else %}
                    <span class="label label-default">Submitted</span>
                {% endif %}
            {% else %}
                <span class="label label-default">Associated</span>
            {% endif %}
        {% endif %}
    </td>

    <td>
        {% if not proposal.cancelled %}
            {% if request.user == proposal.speaker.user and proposal.can_edit %}
                <a href="{% url "proposal_edit" proposal.pk %}" class="btn btn-xs"><i class="fa fa-pencil"></i> Edit</a>
                <a href="{% url "proposal_speaker_manage" proposal.id %}" class="btn btn-xs"><i class="fa fa-user"></i> Manage Additional Speakers</a>
            {% endif %}
        {% endif %}
    </td>
</tr>

symposion2016/templates/symposion/proposals/base.html
{% extends "site_base.html" %}

{% block body_outer %}
    {% block body %}{% endblock %}
{% endblock %}

symposion2016/templates/symposion/proposals/document_create.html
{% extends "symposion/proposals/base.html" %}

{% load bootstrap %}

{% block page_title %}Upload Document to '{{ proposal.title }}'{% endblock %}

{% block body %}
    <form method="POST" action="" enctype="multipart/form-data" class="form form-horizontal">
        {% csrf_token %}
        <fieldset>
            {{ form|bootstrap_horizontal }}
        </fieldset>
        <div class="form-actions">
            <input class="btn btn-primary" type="submit" value="Upload" />
        </div>
    </form>
{% endblock %}

symposion2016/templates/symposion/proposals/proposal_cancel.html
{% extends "symposion/proposals/base.html" %}

{% load i18n %}

{% block head_title %}{% trans 'Cancel Proposal' %}{% endblock %}

{% block body %}
    <h1>Cancel: {{ proposal.title }}</h1>

    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Are you sure you want to cancel <b>{{ proposal.title }}</b>?</p>
        <input class="btn btn-danger" type="submit" value="I am sure" />
        <a class="btn btn-default" href="{% url "proposal_detail" proposal.pk %}">{% trans 'No, keep it for now' %}</a>
    </form>
{% endblock %}

symposion2016/templates/symposion/proposals/proposal_detail.html
{% extends "symposion/proposals/base.html" %}

{% load i18n %}
{% load account_tags %}
{% load bootstrap %}
{% load bleach_tags %}

{% block head_title %}{{ proposal.title }}{% endblock %}

{% block body %}
    <div class="pull-right">
        {% if not proposal.cancelled %}
            {% if request.user == proposal.speaker.user %}
                <a href="{% url "proposal_edit" proposal.pk %}" class="btn btn-default">
                    {% trans "Edit this proposal" %}
                </a>
                <a href="{% url "proposal_cancel" proposal.pk %}" class="btn btn-default">
                    {% trans "Cancel this proposal" %}
                </a>
            {% else %}
                <a href="{% url "proposal_leave" proposal.pk %}" class="btn btn-default">
                    {% trans "Remove me from this proposal" %}
                </a>
            {% endif %}
        {% else %}
            {% trans 'Cancelled' %}
        {% endif %}
    </div>

    <h3>#{{ proposal.number }}: {{ proposal.title }} ({{ proposal.speaker }}, Track: {{ proposal.track }})</h3>

    <div class="tabbable">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#proposal-detail" data-toggle="tab">{% trans "Proposal Details" %}</a></li>
            {% if request.user == proposal.speaker.user %}
                <li><a href="#proposal-documents" data-toggle="tab">{% trans "Supporting Documents" %}</a></li>
            {% endif %}
            {% if message_form %}
                <li><a href="#proposal-feedback" data-toggle="tab">{% trans "Reviewer Feedback" %} <span class="badge">{{ proposal.messages.all|length }}</span></a></li>
            {% endif %}
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="proposal-detail">
                {% include "symposion/proposals/_proposal_fields.html" %}
            </div>
            {% if request.user == proposal.speaker.user %}
                <div class="tab-pane" id="proposal-documents">
                    <h3>{% trans 'Supporting Documents' %}</h3>

                    {% if proposal.supporting_documents.exists %}
                        <table class="table table-striped">
                            {% for document in proposal.supporting_documents.all %}
                                <tr>
                                    <td><a href="{{ document.download_url }}">{{ document.description }}</a></td>
                                    <td>
                                    <form style="margin: 0;" method="post" action="{% url "proposal_document_delete" document.pk %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-xs">{% trans 'delete' %}</button>
                                    </form>
                                </td>
                                </tr>
                            {% endfor %}
                        </table>
                    {% else %}
                        <p>{% trans 'No supporting documents attached to this proposal.' %}</p>
                    {% endif %}
                    <a class="btn btn-sm{% if proposal.cancelled %} btn-disabled{% endif %}" href="{% url "proposal_document_create" proposal.pk %}"><i class="fa fa-upload"></i> {% trans 'Add Document' %}</a>
                </div>
            {% endif %}

    {% if message_form %}
        <div class="tab-pane" id="proposal-feedback">

            <h3>{% trans 'Conversation with Reviewers' %}</h3>

            {% for message in proposal.messages.all %}
                <div class="review-box">
                    <div class="comment">{{ message.message|bleach|linebreaks }}</div>
                    <div class="dateline"><b>{% user_display message.user %}</b> {{ message.submitted_at|timesince }} ago</div>
                </div>
                <div class="clear"></div>
            {% endfor %}

            <h3>{% trans 'Leave a Message' %}</h3>

            <p>{% trans 'You can leave a message for the reviewers here.' %}</p>

            <form action="" method="POST" accept-charset="utf-8">
                {% csrf_token %}
                <fieldset>
                    {{ message_form|bootstrap }}
                </fieldset>
                <div class="actions">
                    <button type="submit" name="message_submit" class="btn btn-primary">{% trans 'Submit' %}</button>
                </div>
            </form>
        </div>
    {% endif %}
    </div>
</div>
{% endblock %}

{% block extra_script %}
    <script src="{{ STATIC_URL }}symposion/js/jquery.history.js"></script>
    <script type="text/javascript">
        $(function() {
            var History = window.History;

            $(window).bind("anchorchange", function() {
                $(".nav-tabs a[href='" + location.hash + "']").click();
            });

            $('#.nav-tabs a[data-toggle="tab"]').on('shown', function (e) {
                if (History.enabled) {
                    History.pushState(null, null, $(e.target).attr("href"));
                }
            });
        });
    </script>
{% endblock extra_script %}

symposion2016/templates/symposion/proposals/proposal_edit.html
{% extends "symposion/proposals/base.html" %}

{% load bootstrap %}

{% block head_title %}Editing {{ proposal.title }}{% endblock %}

{% block body %}
    <h1>Edit: {{ proposal.title }}</h1>

    <p><a href="{% url "proposal_speaker_manage" proposal.pk %}">Manage speakers</a></p>

    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
            {{ form|bootstrap }}
        </fieldset>
        <div class="form-actions">
            <input class="btn btn-primary" type="submit" value="Save" />
            <a class="btn btn-default" href="{% url "proposal_detail" proposal.pk %}">Cancel</a>
        </div>
    </form>
{% endblock %}

symposion2016/templates/symposion/proposals/proposal_leave.html
{% extends "symposion/proposals/base.html" %}

{% block body %}
    <h3>Leaving {{ proposal.title }}</h3>

    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Are you sure you wish to leave as a speaker on <b>{{ proposal.title }}</b>?</p>
        <input type="submit" class="btn btn-primary" value="I am sure" />
    </form>
{% endblock %}

symposion2016/templates/symposion/proposals/proposal_speaker_manage.html
{% extends "symposion/proposals/base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block body %}
    <h1>{% trans 'Proposal:' %} {{ proposal.title }}</h1>

    <p>
      <a href="{% url "proposal_edit" proposal.pk %}">{% trans 'Edit proposal' %}
      </a>
    </p>

    <h2>{% trans 'Current Speakers' %}</h2>

    {% for speaker in speakers %}
        {% if speaker.user %}
            <p><b>{{ speaker.name }}</b> &mdash; {{ speaker.email }}</p>
        {% else %}
            <p>{{ speaker.email }} &mdash; {% trans 'pending invitation' %}</p>
        {% endif %}
    {% endfor %}

    <h2>{% trans 'Add another speaker' %}</h2>

    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ add_speaker_form|bootstrap }}
        <div class="form-action">
            <input type="submit" value="Add speaker" class="btn btn-primary" />
        </div>
    </form>
{% endblock %}

{% block extra_body %}
    <script type="text/javascript">
    $(function() {
        $("#id_email").focus();
    });
    </script>
{% endblock %}

symposion2016/templates/symposion/proposals/proposal_submit.html
{% extends "symposion/proposals/base.html" %}

{% load pinax_boxes_tags %}
{% load i18n %}

{% block page_title %}{% trans "Submit A Proposal" %}{% endblock %}

{% block body %}
    {% box "proposal_submit" %}

    {% if kinds %}
        <p>Select what kind of proposal you'd like to submit:</p>

        <ul>
            {% for kind in kinds %}
                <li><a href="{% url "proposal_submit_kind" kind.slug %}">{{ kind }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Proposals are not currently open for submission.</p>
    {% endif %}
{% endblock %}

symposion2016/templates/symposion/proposals/proposal_submit_kind.html
{% extends "symposion/proposals/base.html" %}

{% load bootstrap %}
{% load pinax_boxes_tags %}
{% load markitup_tags %}
{% load i18n %}

{% block page_title %}Submit a Proposal for a {{ kind.name }}{% endblock %}

{% block body %}
    <div class="page-header">
        <h2>Submit a Proposal</h2>
    </div>
    
    {% box "example_proposal" %}

    <form method="POST" action="" enctype="multipart/form-data" class="form-horizontal">
        {% csrf_token %}
        <fieldset>
            {{ proposal_form|bootstrap_horizontal }}
        </fieldset>
        <div class="form-actions">
            <p>
                You will be able to edit your proposal after it has been submitted. The program committee may ask questions, provide feedback, and even suggest changes to your proposal as part of the review processes.
            </p>
            <input class="btn btn-primary" type="submit" name="finish" value="Save" />
            <!-- <span style="float: right; padding: 4px 6px">or</span> -->
            <input class="btn btn-default" type="submit" name="add-speakers" value="Save and Add Additional Speakers" />
        </div>
    </form>
{% endblock %}